[server]
  port = 8080
  config_file = "config.toml"

[[devices]]
  id = "dev-001"
  host = "192.168.1.10"
  alias = "Server Room KVM"
  username = "admin"

[[devices]]
  id = "dev-002"
  host = "192.168.1.20"
  alias = "Data Center A"
  username = "root"

[[devices]]
  id = "dev-003"
  host = "10.0.0.50"
  alias = "Lab Server"

[[devices]]
  id = "dev-004"
  host = "kvm-rack1.local"
  alias = "Rack 1 Console"
  username = "admin"

[[devices]]
  id = "dev-005"
  host = "192.168.2.100"
  alias = "Dev Environment"

[[devices]]
  id = "dev-006"
  host = "10.10.10.5"
  alias = "Production DB"
  username = "dbadmin"

[[devices]]
  id = "dev-007"
  host = "kvm-office.local"
  alias = "Office Workstation"

[[devices]]
  id = "dev-008"
  host = "192.168.50.1"
  alias = "Network Switch"
  username = "admin"

[[devices]]
  id = "dev-009"
  host = "10.0.1.25"
  alias = "Backup Server"

[[devices]]
  id = "dev-010"
  host = "kvm-test.local"
  alias = "Test Bench"
  username = "tester"

[[devices]]
  id = "1a663881-01f3-44d9-9ac6-9e4ff1706989"
  host = "10.1.1.10"
  alias = "Spark"
